In [2]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
import plotly.io as pio # Useng for animation
from collections import Counter
from scipy import interpolate

In [3]:
file = 'C:/Users/Burger/source/work/double-propellers-and-rings/2СВК/T/Calculation Results/T1/Vн = 0-12.5/25.csv'
new_df = pd.read_csv(file, sep = ',',skiprows=3)
new_df =new_df.apply(pd.to_numeric, errors = 'coerce')

df = pd.DataFrame(new_df.iloc[:,1:])
df.rename({'P3': 'Vн [км/ч]', 'P1': 'h1 [град]', 'P4': 'n1 [об/мин]', 'P2': 'h2 [град]', 'P5': 'n2 [об/мин]',
            'P6': 'ТВ1 [Н]','P7': 'ТВ2 [Н]', 'P8': 'RК1 [Н]','P9': 'RК2 [Н]',
             'P10': 'R ВМГ [Н]', 'P11': 'R тела [Н]','P12': 'R суммарная [Н]', 
             'P13': 'Mx1 [Н*м]', 'P14': 'Mx2 [Н*м]',  'P15': 'Mx ВМГ [Н*м]', 'P16': 'Mx суммарная [Н*м]',
             }, axis=1, inplace=True) 
df.loc[(df['n1 [об/мин]'] == 0.01), 'n1 [об/мин]'] = 0 
df.loc[(df['n2 [об/мин]'] == -0.01), 'n2 [об/мин]'] = 0    

df = df.reindex(columns=['Vн [км/ч]', 'h1 [град]', 'n1 [об/мин]', 'h2 [град]', 'n2 [об/мин]', 'ТВ1 [Н]','ТВ2 [Н]', 'RК1 [Н]','RК2 [Н]',
             'R ВМГ [Н]', 'R тела [Н]','R суммарная [Н]', 
            'Mx1 [Н*м]', 'Mx2 [Н*м]',  'Mx ВМГ [Н*м]', 'Mx суммарная [Н*м]',])

df.head()

,Vн [км/ч],h1 [град],n1 [об/мин],h2 [град],n2 [об/мин],ТВ1 [Н],ТВ2 [Н],RК1 [Н],RК2 [Н],R ВМГ [Н],R тела [Н],R суммарная [Н],Mx1 [Н*м],Mx2 [Н*м],Mx ВМГ [Н*м],Mx суммарная [Н*м]
0,0.0,20.0,0.0,-20.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.0,20.0,0.0,-20.0,-250.0,-2.272180,15.828586,2.743688,6.489046,21.561016,-0.520261,21.040754,0.057459,0.625489,0.002963,0.371380
2,0.0,20.0,0.0,-20.0,-500.0,-8.966804,70.468399,11.817555,24.838531,92.857040,-3.513707,89.343338,0.222875,2.578087,-0.015717,1.784900
3,0.0,20.0,0.0,-20.0,-750.0,-20.607927,160.235570,27.454420,55.535496,210.548260,-7.870735,202.677550,0.514778,5.781661,-0.004668,4.218900
4,0.0,20.0,0.0,-20.0,-1000.0,-36.484676,285.586760,49.519028,99.704613,377.017970,-13.632043,363.385960,0.912347,10.227948,-0.016340,7.681877

In [4]:
# df['h2 [град]'] *=-1
# df['n2 [об/мин]'] *=-1

In [5]:
df_done = pd.DataFrame()
Vx = 0



for i in range (0,6):               # Смотрю куски по Vн
    df_Vx = pd.DataFrame()
    df_Vx = df[(df['Vн [км/ч]'] == Vx)]
    df_h1_2 = pd.DataFrame() 
    h1 = 20
    
    
    for j in range (0,5):               # Смотрю куски по h1
        df_h1_1 = pd.DataFrame()
        df_h1_1 = df_Vx[(df_Vx['h1 [град]'] == h1)]
        

        df_n_1 = pd.DataFrame()
        df_n_2 = pd.DataFrame()
        n = 0

        for k in range (0,5):                                       # Смотрю куски по n1
            df_n_1 = df_h1_1[(df_h1_1['n1 [об/мин]'] == n)]
            n += 250
            df_n_2 = df_n_2.append(df_n_1, ignore_index=True)   
            
        df_h1_2 = df_h1_2.append(df_n_2, ignore_index=True)
        h1 += 2.5

    df_done = df_done.append(df_h1_2, ignore_index=True)    
    Vx += 2.5
# df_done.head(20)

C:\Users\Burger\AppData\Local\Temp\ipykernel_8356\2375462489.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_n_2 = df_n_2.append(df_n_1, ignore_index=True)
C:\Users\Burger\AppData\Local\Temp\ipykernel_8356\2375462489.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_h1_2 = df_h1_2.append(df_n_2, ignore_index=True)
C:\Users\Burger\AppData\Local\Temp\ipykernel_8356\2375462489.py:30: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_done = df_done.append(df_h1_2, ignore_index=True)

In [6]:
df_done.head(464324223)

,Vн [км/ч],h1 [град],n1 [об/мин],h2 [град],n2 [об/мин],ТВ1 [Н],ТВ2 [Н],RК1 [Н],RК2 [Н],R ВМГ [Н],R тела [Н],R суммарная [Н],Mx1 [Н*м],Mx2 [Н*м],Mx ВМГ [Н*м],Mx суммарная [Н*м]
0,0.0,20.0,0.0,-20.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.0,20.0,0.0,-20.0,-250.0,-2.272180,15.828586,2.743688,6.489046,21.561016,-0.520261,21.040754,0.057459,0.625489,0.002963,0.371380
2,0.0,20.0,0.0,-20.0,-500.0,-8.966804,70.468399,11.817555,24.838531,92.857040,-3.513707,89.343338,0.222875,2.578087,-0.015717,1.784900
3,0.0,20.0,0.0,-20.0,-750.0,-20.607927,160.235570,27.454420,55.535496,210.548260,-7.870735,202.677550,0.514778,5.781661,-0.004668,4.218900
4,0.0,20.0,0.0,-20.0,-1000.0,-36.484676,285.586760,49.519028,99.704613,377.017970,-13.632043,363.385960,0.912347,10.227948,-0.016340,7.681877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3745,12.5,30.0,1000.0,-30.0,0.0,421.585000,-122.087000,63.242700,-71.311900,229.001000,-123.523000,105.478000,-21.012400,-3.436570,-16.288400,-16.285600
3746,12.5,30.0,1000.0,-30.0,-250.0,419.388000,-92.933200,62.462800,-61.879300,266.655000,-128.727000,137.928000,-21.084200,-2.092050,-14.032700,-14.030300
3747,12.5,30.0,1000.0,-30.0,-500.0,421.525000,-32.877700,52.484100,-54.078200,335.126000,-132.252000,202.875000,-21.242400,0.745376,-12.710900,-12.709000
3748,12.5,30.0,1000.0,-30.0,-750.0,426.802000,108.716000,40.441000,-37.744900,492.311000,-137.161000,355.150000,-21.480000,8.842190,-8.223570,-8.222180
3749,12.5,30.0,1000.0,-30.0,-1000.0,409.849000,346.611000,34.052700,-1.228080,743.149000,-150.596000,592.554000,-21.126600,21.258900,0.230552,0.230910

### Добавление R тела от М1

In [7]:
# Vx = 5
# df_1 = pd.DataFrame()
# df_2 = pd.DataFrame()

# for i in range (0,4):
#     df_1 = df_done[(df_done['Vн [км/ч]'] == Vx)]
#     if Vx == 5:
#         df_1['R тела [Н]'] += -57.62
#         df_1['R суммарная [Н]'] += -57.62
#     elif Vx == 7.5:
#         df_1["R тела [Н]"] += -129.36
#         df_1["R суммарная [Н]"] += -129.36
#     elif Vx == 10:
#         df_1["R тела [Н]"] += -228.39
#         df_1["R суммарная [Н]"] += -228.39
#     elif Vx == 12.5:
#         df_1["R тела [Н]"] += -354.09
#         df_1["R суммарная [Н]"] += -354.09

#     df_2 = df_2.append(df_1, ignore_index=True)    
#     Vx += 2.5
# df_2.head()

In [9]:
df_done.to_csv('Т1, Vн [0-12.5].csv')